version: "3.9"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PW}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
    command: [ "npm", "start" ]

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PW}
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "sapassword", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
