
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"tam@gmail.com",
    "password":"tam123"
}

###

GET http://localhost:3000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0YW1AZ21haWwuY29tIiwiaWF0IjoxNzU1NTEzMTk3LCJleHAiOjE3NTYxMTc5OTd9._tK8Als7WqPOWmhdKCrStEaoop7u1mtX61sOIy_IPv4
###
POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0YW1AZ21haWwuY29tIiwiaWF0IjoxNzU1NTEzMTc2fQ.Y6QxRNWZz0wFInJmxHNtjFY_ZhZWjWkU5qLuejqCR38"
}