# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test BE CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  building:
    
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repo
       uses: actions/checkout@v3
     - name: Use Node.js 18
       uses: actions/setup-node@v3
       with:
          node-version: "18"
     - name: Clean and Install dependencies
       run: npm ci 

     -  name: Syntax check
        run: npx tsc --noEmit || echo "No TS, skipping" && node -c index.js

     - name: Lint check
       run: npm run lint || echo "No lint script yet"

     - name: Build app
       run: npm run build || echo "No build step yet"
